language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false

addons:
  apt:
    packages:
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

# uncomment the following lines to override the default test script
